CREATE TABLE ITEM_FISCAL_E_CATEGORIA (
	ID_ITEM_FISCAL BIGINT(20) NOT NULL,
	ID_CATEGORIA_FISCAL BIGINT(20) NOT NULL,
	PRIMARY KEY (ID_ITEM_FISCAL, ID_CATEGORIA_FISCAL),
	CONSTRAINT FK_ITEM_FISCAL FOREIGN KEY (ID_ITEM_FISCAL) REFERENCES ITEM_FISCAL (ID) ON UPDATE RESTRICT ON DELETE CASCADE,
	CONSTRAINT FK_CATEGORIA_FISCAL FOREIGN KEY (ID_CATEGORIA_FISCAL) REFERENCES CATEGORIA_FISCAL (ID) ON UPDATE RESTRICT ON DELETE CASCADE
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;
