INSERT INTO ITEM_FISCAL_E_CATEGORIA (ID_ITEM_FISCAL, ID_CATEGORIA_FISCAL) VALUES (2, 4);
INSERT INTO ITEM_FISCAL_E_CATEGORIA (ID_ITEM_FISCAL, ID_CATEGORIA_FISCAL) VALUES (2, 5);
INSERT INTO ITEM_FISCAL_E_CATEGORIA (ID_ITEM_FISCAL, ID_CATEGORIA_FISCAL) VALUES (2, 6);
INSERT INTO ITEM_FISCAL_E_CATEGORIA (ID_ITEM_FISCAL, ID_CATEGORIA_FISCAL) VALUES (2, 8);
INSERT INTO ITEM_FISCAL_E_CATEGORIA (ID_ITEM_FISCAL, ID_CATEGORIA_FISCAL) VALUES (2, 10);
INSERT INTO ITEM_FISCAL_E_CATEGORIA (ID_ITEM_FISCAL, ID_CATEGORIA_FISCAL) VALUES (2, 12);

INSERT INTO ITEM_FISCAL_E_CATEGORIA (ID_ITEM_FISCAL, ID_CATEGORIA_FISCAL) VALUES (1, 7);
INSERT INTO ITEM_FISCAL_E_CATEGORIA (ID_ITEM_FISCAL, ID_CATEGORIA_FISCAL) VALUES (1, 8);
INSERT INTO ITEM_FISCAL_E_CATEGORIA (ID_ITEM_FISCAL, ID_CATEGORIA_FISCAL) VALUES (1, 9);
INSERT INTO ITEM_FISCAL_E_CATEGORIA (ID_ITEM_FISCAL, ID_CATEGORIA_FISCAL) VALUES (1, 10);
INSERT INTO ITEM_FISCAL_E_CATEGORIA (ID_ITEM_FISCAL, ID_CATEGORIA_FISCAL) VALUES (1, 11);
INSERT INTO ITEM_FISCAL_E_CATEGORIA (ID_ITEM_FISCAL, ID_CATEGORIA_FISCAL) VALUES (1, 12);
