INSERT INTO PRODUTO (ID, DESCRICAO, VALOR_UNITARIO, ID_CATEGORIA_FISCAL) VALUES (1, 'Pìpos Vitaminado', 2.29, 1);
INSERT INTO PRODUTO (ID, DESCRICAO, VALOR_UNITARIO, ID_CATEGORIA_FISCAL) VALUES (2, 'Arroz Tio João', 4.48, 1);
INSERT INTO PRODUTO (ID, DESCRICAO, VALOR_UNITARIO, ID_CATEGORIA_FISCAL) VALUES (3, 'Fiejão Ki Kaldo', 4.88, 1);
INSERT INTO PRODUTO (ID, DESCRICAO, VALOR_UNITARIO, ID_CATEGORIA_FISCAL) VALUES (4, 'Chocolate Garoto', 12.49, 1);
INSERT INTO PRODUTO (ID, DESCRICAO, VALOR_UNITARIO, ID_CATEGORIA_FISCAL) VALUES (5, 'A Arte da Guerra', 25.00, 2);
INSERT INTO PRODUTO (ID, DESCRICAO, VALOR_UNITARIO, ID_CATEGORIA_FISCAL) VALUES (6, 'Harry Potter e a pedra filosofal', 80.89, 2);
INSERT INTO PRODUTO (ID, DESCRICAO, VALOR_UNITARIO, ID_CATEGORIA_FISCAL) VALUES (7, 'Chocolate Belga (importado)', 10, 4);
INSERT INTO PRODUTO (ID, DESCRICAO, VALOR_UNITARIO, ID_CATEGORIA_FISCAL) VALUES (8, 'Perfume Francês (importado)', 47.50, 12);
INSERT INTO PRODUTO (ID, DESCRICAO, VALOR_UNITARIO, ID_CATEGORIA_FISCAL) VALUES (9, 'Perfume Italiano (importado)', 27.99, 12);
INSERT INTO PRODUTO (ID, DESCRICAO, VALOR_UNITARIO, ID_CATEGORIA_FISCAL) VALUES (10, 'CD do Raça Negra', 14.99, 8);
INSERT INTO PRODUTO (ID, DESCRICAO, VALOR_UNITARIO, ID_CATEGORIA_FISCAL) VALUES (11, 'Perfume alma de rosas', 18.99, 11);
INSERT INTO PRODUTO (ID, DESCRICAO, VALOR_UNITARIO, ID_CATEGORIA_FISCAL) VALUES (12, 'Dorflex', 9.75, 3);
INSERT INTO PRODUTO (ID, DESCRICAO, VALOR_UNITARIO, ID_CATEGORIA_FISCAL) VALUES (13, 'Caixa de chocolate Francês (importado)', 10, 4);

