CREATE TABLE ITEM_FISCAL (
	ID BIGINT(20) auto_increment NOT NULL,
	DESCRICAO varchar(100) NOT NULL,
	PERCENTUAL DECIMAL NOT NULL,
	PRIMARY KEY (ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;
