CREATE TABLE PRODUTO (
	ID BIGINT(20) auto_increment NOT NULL,
	DESCRICAO VARCHAR(100) NOT NULL,
	VALOR_UNITARIO DECIMAL(10,2) NOT NULL,
	ID_CATEGORIA_FISCAL BIGINT(20) NULL,
	PRIMARY KEY (ID),
	CONSTRAINT FK_PROD_CATEG_FISC FOREIGN KEY (ID_CATEGORIA_FISCAL) REFERENCES CATEGORIA_FISCAL (ID)  ON UPDATE RESTRICT ON DELETE CASCADE
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;
