INSERT INTO CATEGORIA_FISCAL (ID, DESCRICAO) VALUES (1, 'COMIDA');
INSERT INTO CATEGORIA_FISCAL (ID, DESCRICAO) VALUES (2, 'LIVRO');
INSERT INTO CATEGORIA_FISCAL (ID, DESCRICAO) VALUES (3, 'PRODUTO MÉDICO');

INSERT INTO CATEGORIA_FISCAL (ID, DESCRICAO) VALUES (4, 'COMIDA IMPORTADO');
INSERT INTO CATEGORIA_FISCAL (ID, DESCRICAO) VALUES (5, 'LIVRO IMPORTADO');
INSERT INTO CATEGORIA_FISCAL (ID, DESCRICAO) VALUES (6, 'PRODUTO MÉDICO IMPORTADO');

INSERT INTO CATEGORIA_FISCAL (ID, DESCRICAO) VALUES (7, 'ELETRONICOS');
INSERT INTO CATEGORIA_FISCAL (ID, DESCRICAO) VALUES (8, 'ELETRONICOS IMPORTADO');

INSERT INTO CATEGORIA_FISCAL (ID, DESCRICAO) VALUES (9, 'CD/DVDS');
INSERT INTO CATEGORIA_FISCAL (ID, DESCRICAO) VALUES (10, 'CD/DVDS IMPORTADO');

INSERT INTO CATEGORIA_FISCAL (ID, DESCRICAO) VALUES (11, 'PERFUME');
INSERT INTO CATEGORIA_FISCAL (ID, DESCRICAO) VALUES (12, 'PERFUME IMPORTADO');
